# -*- coding: utf-8 -*-
"""Kaggle Competition-2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzcK73PH8MLqEjkadUVacS692EDIwvLt
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st

st.title("Customer Segmentation")


df = pd.read_csv("Mall_Customers.csv")
df

#Dropping unnecessary columns
df.drop("CustomerID",axis=1,inplace=True)
df

from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering

# Select features for clustering (Annual Income & Spending Score)
X = df[['Annual Income (k$)', 'Spending Score (1-100)']].values

# 3️Standardize the data for better distance calculations
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled)
X_scaled

# Compute the distance matrix and plot the dendrogram
linked = linkage(X_scaled, method='ward')  # Ward’s method minimizes variance

plt.figure(figsize=(10, 5))
dendrogram(linked, truncate_mode='level', p=5, show_leaf_counts=True)
plt.title("Dendrogram for Hierarchical Clustering")
plt.xlabel("Customer Index")
plt.ylabel("Distance")
plt.show()

#  Choose the number of clusters based on dendrogram and apply clustering
num_clusters = 5  # Adjust based on dendrogram cutoff
hc = AgglomerativeClustering(n_clusters=num_clusters, metric='euclidean', linkage='ward')
df['Cluster'] = hc.fit_predict(X_scaled)

# Visualizing Clusters
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X[:, 0], y=X[:, 1], hue=df['Cluster'], palette='viridis', s=100)
plt.title("Customer Segmentation using Hierarchical Clustering")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.legend(title="Cluster")
plt.show()

from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(X_scaled, df['Cluster'])

print(f"Silhouette Score for {num_clusters} clusters: {silhouette_avg:.4f}")
