# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfuCi7cB7zeKIWiHep_B9DBwHbaQXe3k
"""
# streamlit_app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set Streamlit page config
st.set_page_config(page_title="Customer Analysis", layout="wide")




# ✅ Now write your title using Streamlit
st.title("Customer Behavior Uncovered: Trends You Can't Ignore")


# Load the data
df = pd.read_csv("ecommerce_customer_data.csv")


st.markdown("""
<div style="background-image: url('https://www.transparenttextures.com/patterns/cubes.png'); padding: 10px 20px; border-radius: 10px;">
    <h2 style="color: 88304E;">Understanding Customer Diversity</h2>
    <p style="color: F7374F; font-size: 16px; font-family: 'Arial';">
    Analyzing age, gender, and location patterns to better understand our customer base.
    </p>
</div>
""", unsafe_allow_html=True)


# Gender-wise Distribution
st.subheader("Gender-wise Customer Distribution")

gender_distribution = df['Gender'].value_counts().reset_index()
gender_distribution.columns = ['Gender', 'Count']

fig1, ax1 = plt.subplots()
sns.barplot(x='Gender', y='Count', data=gender_distribution, palette='pastel', ax=ax1)
ax1.set_title("Gender-wise Customer Distribution")
ax1.set_xlabel("Gender")
ax1.set_ylabel("No. of Customers")
st.pyplot(fig1)

# Location-wise Distribution
st.subheader("Location-wise Customer Distribution")

location_dist = df['Location'].value_counts().reset_index()
location_dist.columns = ['Location', 'Count']

fig2, ax2 = plt.subplots(figsize=(10,5))
sns.barplot(x='Location', y='Count', data=location_dist, palette='viridis', ax=ax2)
ax2.set_title("Location-wise Customer Distribution")
ax2.set_xlabel("Location")
ax2.set_ylabel("No. of Customers")
plt.xticks(rotation=45, ha='right')
st.pyplot(fig2)




st.markdown("""
<div style="background-image: url('https://www.transparenttextures.com/patterns/cubes.png'); padding: 10px 20px; border-radius: 10px;">
    <h2 style="color: 88304E;">Customer Browsing and Engagement Trends</h2>
    <p style="color: F7374F; font-size: 16px; font-family: 'Arial';">
    Exploring how customers interact with our platform through browsing behavior and engagement metrics.
    </p>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div style="background-image: url('https://www.transparenttextures.com/patterns/cubes.png'); padding: 10px 20px; border-radius: 10px;">
    <h2 style="color: 88304E;">Transactional Insights: Frequency and Preferences</h2>
    <p style="color: F7374F; font-size: 16px; font-family: 'Arial';">
    Uncovering purchase habits, spending patterns, and product preferences across customers.
    </p>
</div>
""", unsafe_allow_html=True)
