# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZfuCi7cB7zeKIWiHep_B9DBwHbaQXe3k
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("ecommerce_customer_data.csv")
df

df.info()

"""''' Task - Your task involves:

1.Understanding the distribution and characteristics of customer demographics (e.g., age, gender, location).
2.Exploring how different types of devices are used by customers and their impact on behavior.
3.Investigating the relationship between browsing time, pages viewed, items added to the cart, and actual purchases.
4.Segmenting customers based on their behavior and identifying distinct customer groups.
5.Analyzing the customer journey and identifying potential areas for improvement in the conversion funnel.
6.Assessing the impact of customer behavior on revenue generation and identifying opportunities for increasing sales and customer engagement.
'''
"""

gender_distribution = df['Gender'].value_counts().reset_index()
gender_distribution.columns = ['Gender', 'Count']
sns.barplot(x='Gender',y='Count',data = gender_distribution, palette = 'pastel')
plt.title("Gender-wise Customer distribution:")
plt.xlabel("Gender")
plt.ylabel("No. of customers")
plt.show()

df['Age'].max()

location_dist = df['Location'].value_counts().reset_index()
location_dist.columns = ('Location','Count')
sns.barplot(x='Location',y='Count',data=location_dist,palette='viridis')
plt.title("Location-wise Customer distribution")
plt.xticks(rotation= 45, ha='right')
plt.xlabel("Location")
plt.ylabel("No. of Customers")
plt.show()

df['Device_Type'].value_counts()

